#!/usr/bin/bash
# Writen by: Michael Williams <draringi@draringi.net>
DEFAULT_DB=/usr/share/codejam/2014/setA.yml.gz

if [[ -z "$1" ]]
then
	echo "USAGE: $0 FACE_IMG [DB_FILE]"
	echo "FACE_IMG: Path to image of face"
	echo "DB_FILE: Path to Known Faces Database (Optional)"
	exit 1
fi
FACE_IMG=$1
if [[ -z "$2" ]]
then
	DB_FILE=$DEFAULT_DB
else
	DB_FILE=$2
fi
CLEANED_FACE=$(facerecog-cleaner "$FACE_IMG" 1)
if [[ -z "$CLEANED_FACE" ]]
then
	ID=-2
else
	ID=$(facerecog "$CLEANED_FACE" "$DB_FILE")
fi

if [[ "$ID" == "-2" ]]
then
	echo "DENIED: No Face Detected"
elif [[ "$ID" == "-1" ]]
then
	echo "DENIED: Unknown Face"
else
	echo $ID
fi
